language: android
android:
    components:
        - platform-tools
        - build-tools-23.0.1
        - android-23
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

script:
    - ./PluriLockItup/gradle build connectedCheck
